<a href="https://colab.research.google.com/github/ahnjonghyunn/ABC/blob/main/03_%EB%8C%80%EC%A0%84%EA%B4%91%EC%97%AD%EC%8B%9C_%EC%9D%B8%EA%B5%AC_%EB%B6%84%EC%84%9D%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

데이터 준비하기

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
df=pd.read_csv('/content/200812_202112_주민등록인구및세대현황_대전.csv',encoding='cp949')
df.head()

,행정구역,2008년_총인구수,2008년_세대수,2008년_세대당 인구,2008년_남자 인구수,2008년_여자 인구수,2008년_남여 비율,2009년_총인구수,2009년_세대수,2009년_세대당 인구,...,2020년_세대당 인구,2020년_남자 인구수,2020년_여자 인구수,2020년_남여 비율,2021년_총인구수,2021년_세대수,2021년_세대당 인구,2021년_남자 인구수,2021년_여자 인구수,2021년_남여 비율
0,동구,245973,94402,2.61,124816,121157,1.03,246116,95415,2.58,...,2.11,112416,110605,1.02,222222,107832,2.06,111953,110269,1.02
1,중구,264678,97719,2.71,132139,132539,1.00,264035,98373,2.68,...,2.19,116233,119317,0.97,230341,107609,2.14,113507,116834,0.97
2,서구,499172,174265,2.86,246386,252786,0.97,499297,176293,2.83,...,2.28,235112,242768,0.97,473365,213592,2.22,232714,240651,0.97
3,유성구,259831,91153,2.85,131143,128688,1.02,266585,93906,2.84,...,2.32,177240,173807,1.02,351277,155450,2.26,177463,173814,1.02
4,대덕구,211241,74143,2.85,107127,104114,1.03,208147,74113,2.81,...,2.26,89698,86686,1.03,175046,79934,2.19,88989,86057,1.03

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 85 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   행정구역          5 non-null      object
 1   2008년_총인구수    5 non-null      int64
 2   2008년_세대수     5 non-null      int64
 3   2008년_세대당 인구  5 non-null      float64
 4   2008년_남자 인구수  5 non-null      int64
 5   2008년_여자 인구수  5 non-null      int64
 6   2008년_남여 비율   5 non-null      float64
 7   2009년_총인구수    5 non-null      int64
 8   2009년_세대수     5 non-null      int64
 9   2009년_세대당 인구  5 non-null      float64
 10  2009년_남자 인구수  5 non-null      int64
 11  2009년_여자 인구수  5 non-null      int64
 12  2009년_남여 비율   5 non-null      float64
 13  2010년_총인구수    5 non-null      int64
 14  2010년_세대수     5 non-null      int64
 15  2010년_세대당 인구  5 non-null      float64
 16  2010년_남자 인구수  5 non-null      int64
 17  2010년_여자 인구수  5 non-null      int64
 18  2010년_남여 비율   5 non-null      float64
 19  2011년_총인구수    5 non-null      int64
 20  2011년_세대수     5 non-null      int64
 21  2011년_세대당 인구  5 non-null      float64
 22  2011년_남자 인구수  5 non-null      int64
 23  2011년_여자 인구수  5 non-null      int64
 24  2011년_남여 비율   5 non-null      float64
 25  2012년_총인구수    5 non-null      int64
 26  2012년_세대수     5 non-null      int64
 27  2012년_세대당 인구  5 non-null      float64
 28  2012년_남자 인구수  5 non-null      int64
 29  2012년_여자 인구수  5 non-null      int64
 30  2012년_남여 비율   5 non-null      float64
 31  2013년_총인구수    5 non-null      int64
 32  2013년_세대수     5 non-null      int64
 33  2013년_세대당 인구  5 non-null      float64
 34  2013년_남자 인구수  5 non-null      int64
 35  2013년_여자 인구수  5 non-null      int64
 36  2013년_남여 비율   5 non-null      float64
 37  2014년_총인구수    5 non-null      int64
 38  2014년_세대수     5 non-null      int64
 39  2014년_세대당 인구  5 non-null      float64
 40  2014년_남자 인구수  5 non-null      int64
 41  2014년_여자 인구수  5 non-null      int64
 42  2014년_남여 비율   5 non-null      float64
 43  2015년_총인구수    5 non-null      int64
 44  2015년_세대수     5 non-null      int64
 45  2015년_세대당 인구  5 non-null      float64
 46  2015년_남자 인구수  5 non-null      int64
 47  2015년_여자 인구수  5 non-null      int64
 48  2015년_남여 비율   5 non-null      float64
 49  2016년_총인구수    5 non-null      int64
 50  2016년_세대수     5 non-null      int64
 51  2016년_세대당 인구  5 non-null      float64
 52  2016년_남자 인구수  5 non-null      int64
 53  2016년_여자 인구수  5 non-null      int64
 54  2016년_남여 비율   5 non-null      float64
 55  2017년_총인구수    5 non-null      int64
 56  2017년_세대수     5 non-null      int64
 57  2017년_세대당 인구  5 non-null      float64
 58  2017년_남자 인구수  5 non-null      int64
 59  2017년_여자 인구수  5 non-null      int64
 60  2017년_남여 비율   5 non-null      float64
 61  2018년_총인구수    5 non-null      int64
 62  2018년_세대수     5 non-null      int64
 63  2018년_세대당 인구  5 non-null      float64
 64  2018년_남자 인구수  5 non-null      int64
 65  2018년_여자 인구수  5 non-null      int64
 66  2018년_남여 비율   5 non-null      float64
 67  2019년_총인구수    5 non-null      int64
 68  2019년_세대수     5 non-null      int64
 69  2019년_세대당 인구  5 non-null      float64
 70  2019년_남자 인구수  5 non-null      int64
 71  2019년_여자 인구수  5 non-null      int64
 72  2019년_남여 비율   5 non-null      float64
 73  2020년_총인구수    5 non-null      int64
 74  2020년_세대수     5 non-null      int64
 75  2020년_세대당 인구  5 non-null      float64
 76  2020년_남자 인구수  5 non-null      int64
 77  2020년_여자 인구수  5 non-null      int64
 78  2020년_남여 비율   5 non-null      float64
 79  2021년_총인구수    5 non-null      int64
 80  2021년_세대수     5 non-null      int64
 81  2021년_세대당 인구  5 non-null      float64
 82  2021년_남자 인구수  5 non-null      int64
 83  2021년_여자 인구수  5 non-null      int64
 84  2021년_남여 비율   5 non-null      float64
dtypes: float64(28), int64(56), object(1)
memory usage: 3.4+ KB

데이터 전처리

In [ ]:
daejeon_df = df.loc[:,['행정구역',
                       '2008년_총인구수',
                       '2009년_총인구수',
                       '2010년_총인구수',
                       '2011년_총인구수',
                       '2012년_총인구수',
                       '2013년_총인구수',
                       '2014년_총인구수',
                       '2015년_총인구수',
                       '2016년_총인구수',
                       '2017년_총인구수',
                       '2018년_총인구수',
                       '2019년_총인구수',
                       '2020년_총인구수',
                       '2021년_총인구수']]
daejeon_df

,행정구역,2008년_총인구수,2009년_총인구수,2010년_총인구수,2011년_총인구수,2012년_총인구수,2013년_총인구수,2014년_총인구수,2015년_총인구수,2016년_총인구수,2017년_총인구수,2018년_총인구수,2019년_총인구수,2020년_총인구수,2021년_총인구수
0,동구,245973,246116,248835,251285,251945,250653,245493,239579,234959,230516,229071,226771,223021,222222
1,중구,264678,264035,265846,265502,264125,264913,261165,256186,252490,248933,244421,240473,235550,230341
2,서구,499172,499297,499742,499124,496513,498917,496132,490859,491011,487448,484663,481222,477880,473365
3,유성구,259831,266585,281692,294353,306312,313968,327461,335312,343222,348428,349790,349373,351047,351277
4,대덕구,211241,208147,207549,205339,205688,204360,201558,196839,192688,186902,181991,177031,176384,175046

In [ ]:
daejeon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   행정구역        5 non-null      object
 1   2008년_총인구수  5 non-null      int64
 2   2009년_총인구수  5 non-null      int64
 3   2010년_총인구수  5 non-null      int64
 4   2011년_총인구수  5 non-null      int64
 5   2012년_총인구수  5 non-null      int64
 6   2013년_총인구수  5 non-null      int64
 7   2014년_총인구수  5 non-null      int64
 8   2015년_총인구수  5 non-null      int64
 9   2016년_총인구수  5 non-null      int64
 10  2017년_총인구수  5 non-null      int64
 11  2018년_총인구수  5 non-null      int64
 12  2019년_총인구수  5 non-null      int64
 13  2020년_총인구수  5 non-null      int64
 14  2021년_총인구수  5 non-null      int64
dtypes: int64(14), object(1)
memory usage: 728.0+ bytes

In [ ]:
dj_df = daejeon_df.set_index('행정구역').T
dj_df

행정구역            동구      중구      서구     유성구     대덕구
2008년_총인구수  245973  264678  499172  259831  211241
2009년_총인구수  246116  264035  499297  266585  208147
2010년_총인구수  248835  265846  499742  281692  207549
2011년_총인구수  251285  265502  499124  294353  205339
2012년_총인구수  251945  264125  496513  306312  205688
2013년_총인구수  250653  264913  498917  313968  204360
2014년_총인구수  245493  261165  496132  327461  201558
2015년_총인구수  239579  256186  490859  335312  196839
2016년_총인구수  234959  252490  491011  343222  192688
2017년_총인구수  230516  248933  487448  348428  186902
2018년_총인구수  229071  244421  484663  349790  181991
2019년_총인구수  226771  240473  481222  349373  177031
2020년_총인구수  223021  235550  477880  351047  176384
2021년_총인구수  222222  230341  473365  351277  175046

In [ ]:
dj_df.reset_index(drop=False)

행정구역       index      동구      중구      서구     유성구     대덕구
0     2008년_총인구수  245973  264678  499172  259831  211241
1     2009년_총인구수  246116  264035  499297  266585  208147
2     2010년_총인구수  248835  265846  499742  281692  207549
3     2011년_총인구수  251285  265502  499124  294353  205339
4     2012년_총인구수  251945  264125  496513  306312  205688
5     2013년_총인구수  250653  264913  498917  313968  204360
6     2014년_총인구수  245493  261165  496132  327461  201558
7     2015년_총인구수  239579  256186  490859  335312  196839
8     2016년_총인구수  234959  252490  491011  343222  192688
9     2017년_총인구수  230516  248933  487448  348428  186902
10    2018년_총인구수  229071  244421  484663  349790  181991
11    2019년_총인구수  226771  240473  481222  349373  177031
12    2020년_총인구수  223021  235550  477880  351047  176384
13    2021년_총인구수  222222  230341  473365  351277  175046

In [ ]:
dj_df.to_csv('/content/행정구역별_년도별총인구수.csv',encoding='cp949',index_label='연도')

시각화로 보는 인구 이동 및 감소/증가

In [ ]:
fig = px.bar(daejeon_df,
             x="행정구역",
             y=daejeon_df.columns,
             barmode='group',
             text_auto='True',
             title="2008년~2021년까지 대전 인구수 데이터 분석")

fig.show()

In [ ]:
daejeon_total_df = pd.read_csv("/content/행정구역별_년도별총인구수.csv",encoding='CP949')

In [ ]:
fig=px.line(daejeon_total_df,
             x="연도",
             y=['동구','중구','서구','유성구','대덕구'],)

fig.update_layout(title='2008년~2021년 대전 총인구수 데이터 분석',
                  xaxis_title='2008년~2021년',
                  yaxis_title='대전광역시 구별 인구수',
                  autosize=False,
                  width=500,height=500)